"""
Static content data for the OpenOA public website API.
All content is derived from the OpenOA package README and documentation.
"""

# ── Analysis Methods ──────────────────────────────────────────────────────────

ANALYSIS_METHODS = [
    {
        "id": "monte_carlo_aep",
        "name": "MonteCarloAEP",
        "short_description": "Long-term annual energy production estimation with uncertainty quantification.",
        "long_description": (
            "This routine estimates the long-term annual energy production (AEP) of a wind "
            "power plant (typically over 10–20 years) based on operational data from a shorter "
            "period of record (e.g., 1–3 years), along with the uncertainty. The method uses a "
            "Monte Carlo approach to sample from distributions of key inputs and propagate "
            "uncertainty through the AEP calculation."
        ),
        "citations": [
            "Perr-Sauer et al., 2021, JOSS",
            "Lee & Fields, 2021, Wind Energy Science",
        ],
        "parameters": [
            "SCADA data", "Reanalysis data", "Loss estimates", "Uncertainty inputs"
        ],
        "icon": "📊",
    },
    {
        "id": "turbine_long_term_gross_energy",
        "name": "TurbineLongTermGrossEnergy",
        "short_description": "Long-term turbine ideal energy estimation for wind plants.",
        "long_description": (
            "This routine estimates the long-term turbine ideal energy (TIE) of a wind plant, "
            "defined as the long-term AEP that would be generated by the wind plant if all "
            "turbines operated normally (i.e., no downtime, derating, or severe "
            "underperformance, but still subject to wake losses and moderate performance "
            "losses), along with the uncertainty."
        ),
        "citations": ["Bodini et al., 2021, Wind Energy Science"],
        "parameters": ["SCADA data", "Reanalysis data", "Turbine metadata"],
        "icon": "🌬️",
    },
    {
        "id": "electrical_losses",
        "name": "ElectricalLosses",
        "short_description": "Estimates average electrical losses with uncertainty.",
        "long_description": (
            "The ElectricalLosses routine estimates the average electrical losses at a wind "
            "plant, along with the uncertainty, by comparing the energy produced at the wind "
            "turbines to the energy delivered to the grid. This includes transformer losses, "
            "line losses, and other electrical system inefficiencies."
        ),
        "citations": ["Bodini et al., 2021, Wind Energy Science"],
        "parameters": ["SCADA data", "Revenue meter data"],
        "icon": "⚡",
    },
    {
        "id": "eya_gap_analysis",
        "name": "EYAGapAnalysis",
        "short_description": "Gap analysis between pre-construction estimates and actual AEP.",
        "long_description": (
            "This class is used to perform a gap analysis between the estimated AEP from a "
            "pre-construction energy yield assessment (EYA) and the actual AEP. The gap analysis "
            "compares different wind plant performance categories to help understand the sources "
            "of differences between EYA AEP estimates and actual AEP, specifically availability "
            "losses, electrical losses, and turbine ideal energy."
        ),
        "citations": ["Bodini et al., 2021, Wind Energy Science"],
        "parameters": ["EYA estimates", "Operational AEP", "Loss categories"],
        "icon": "📈",
    },
    {
        "id": "wake_losses",
        "name": "WakeLosses",
        "short_description": "Estimates long-term internal wake losses for each turbine.",
        "long_description": (
            "This routine estimates long-term internal wake losses experienced by a wind plant "
            "and for each individual turbine, along with the uncertainty. Wake losses occur when "
            "upstream turbines extract energy from the wind, reducing the energy available to "
            "downstream turbines. Understanding these losses is critical for wind farm layout "
            "optimization and performance assessment."
        ),
        "citations": [
            "Simley et al., 2022, Wind Energy Science",
            "Based in part on approaches by Barthelmie, Jensen, et al.",
        ],
        "parameters": ["SCADA data", "Turbine coordinates", "Wind direction data"],
        "icon": "🌀",
    },
    {
        "id": "static_yaw_misalignment",
        "name": "StaticYawMisalignment",
        "short_description": "Estimates static yaw misalignment for individual turbines.",
        "long_description": (
            "The StaticYawMisalignment routine estimates the static yaw misalignment for "
            "individual wind turbines as a function of wind speed by comparing the estimated "
            "wind vane angle at which power is maximized to the mean wind vane angle at which "
            "the turbines operate. The routine includes uncertainty quantification. "
            "Note: This method has not been fully validated and results should be treated with caution."
        ),
        "citations": ["Based in part on approaches by Wan, Burton, et al."],
        "parameters": ["SCADA data", "Wind vane data", "Power output"],
        "icon": "🧭",
    },
]


# ── Features / Utilities ─────────────────────────────────────────────────────

FEATURES = [
    {
        "id": "plant_data",
        "name": "PlantData Schema",
        "description": (
            "A standardized data model built on Pandas DataFrames that combines raw data from "
            "wind turbines, meteorological towers, revenue meters, and reanalysis products "
            "(MERRA-2, ERA5). Includes automated validation for required data columns and types."
        ),
        "icon": "🗄️",
        "category": "core",
    },
    {
        "id": "quality_assurance",
        "name": "Quality Assurance",
        "description": (
            "Methods for identifying potential quality issues with SCADA data prior to importing "
            "it into a PlantData object. Includes range checks, timestamp validation, and "
            "consistency checks."
        ),
        "icon": "✅",
        "category": "utility",
    },
    {
        "id": "filters",
        "name": "Filters",
        "description": (
            "Functions for flagging and filtering operational data based on a range of criteria "
            "including outlier detection, status code filtering, and range-based flagging."
        ),
        "icon": "🔍",
        "category": "utility",
    },
    {
        "id": "power_curve",
        "name": "Power Curve Fitting",
        "description": (
            "Methods for fitting power curve models to SCADA data, including parametric and "
            "non-parametric approaches. Supports IEC-standard binning and GAM-based models."
        ),
        "icon": "📉",
        "category": "utility",
    },
    {
        "id": "imputing",
        "name": "Data Imputing",
        "description": (
            "Methods for filling in missing data with imputed values using a variety of "
            "approaches including linear interpolation, nearest-neighbor, and regression-based "
            "methods."
        ),
        "icon": "🩹",
        "category": "utility",
    },
    {
        "id": "met_data",
        "name": "Met Data Processing",
        "description": (
            "Methods for processing meteorological data, such as computing air density, "
            "wind shear coefficients, and other derived quantities from met tower and "
            "reanalysis data."
        ),
        "icon": "🌡️",
        "category": "utility",
    },
    {
        "id": "plotting",
        "name": "Plotting & Visualization",
        "description": (
            "Convenient functions for creating standard wind energy plots including power curves, "
            "wind roses, wind plant layout maps, and time series visualizations using Matplotlib "
            "and Bokeh."
        ),
        "icon": "📊",
        "category": "utility",
    },
    {
        "id": "uncertainty",
        "name": "Uncertainty Quantification",
        "description": (
            "Built-in Monte Carlo uncertainty quantification for all analysis methods. "
            "Propagates uncertainty from multiple input sources through the analysis chain."
        ),
        "icon": "📐",
        "category": "core",
    },
]


# ── Documentation Content ────────────────────────────────────────────────────

OVERVIEW = {
    "title": "About OpenOA",
    "content": (
        "OpenOA is an open-source software framework written in Python for assessing wind plant "
        "performance using operational assessment (OA) methodologies that consume time series data "
        "from wind plants. The goal of the project is to provide an open-source implementation of "
        "common data structures, analysis methods, and utility functions relevant to wind plant OA, "
        "while providing a platform to collaborate on new functionality.\n\n"
        "Development of OpenOA was motivated by the Wind Plant Performance Prediction (WP3) "
        "Benchmark project, led by the National Renewable Energy Laboratory (NREL), which focuses "
        "on quantifying and understanding differences between the expected and actual energy "
        "production of wind plants.\n\n"
        "OpenOA is primarily developed with the support of the U.S. Department of Energy and is "
        "part of the WETO Software Stack."
    ),
    "subsections": [
        {
            "title": "Key Goals",
            "items": [
                "Provide a reference implementation of OA methods",
                "Develop and improve data standards",
                "Standardize OA methods and metrics",
                "Support performance benchmarking and gap analysis",
                "Enable portfolio-level analysis",
            ],
        },
        {
            "title": "Supported Data Sources",
            "items": [
                "SCADA turbine data",
                "Meteorological (met) tower data",
                "Revenue meter data",
                "Reanalysis products (MERRA-2, ERA5)",
            ],
        },
    ],
}

INSTALLATION = {
    "title": "Installation",
    "content": (
        "OpenOA requires Python 3.10 or later. It can be installed via pip from PyPI."
    ),
    "subsections": [
        {
            "title": "Quick Install",
            "code": "pip install openoa",
        },
        {
            "title": "Install from Source",
            "code": (
                "git clone https://github.com/NREL/OpenOA.git\n"
                "cd OpenOA\n"
                "pip install ."
            ),
        },
        {
            "title": "Development Install",
            "code": (
                "git clone https://github.com/NREL/OpenOA.git\n"
                "cd OpenOA\n"
                'pip install -e ".[develop]"'
            ),
        },
    ],
}

SCHEMA_INFO = {
    "title": "PlantData Schema",
    "content": (
        "OpenOA contains a PlantData class based on Pandas DataFrames that provides a "
        "standardized base schema to combine raw data from wind turbines, meteorological "
        "towers, revenue meters, and reanalysis products. The PlantData class can perform "
        "basic validation for the data required to perform the operational analyses.\n\n"
        "The schema defines required and optional columns for each data type, along with "
        "expected dtypes, units, and value ranges."
    ),
    "subsections": [
        {
            "title": "Data Tables",
            "items": [
                "scada — Turbine-level SCADA data (power, wind speed, nacelle direction, etc.)",
                "meter — Revenue meter data (energy delivered to the grid)",
                "tower — Met tower data (wind speed, wind direction, temperature, pressure)",
                "curtail — Curtailment data",
                "reanalysis — Reanalysis data (wind speed, wind direction, temperature, density)",
                "asset — Turbine metadata (location, hub height, rotor diameter, rated power)",
            ],
        },
    ],
}

CITATIONS = {
    "title": "How to Cite OpenOA",
    "content": (
        "If you use OpenOA in your research, please cite the following paper:"
    ),
    "subsections": [
        {
            "title": "Primary Citation",
            "text": (
                "Perr-Sauer, J., Optis, M., Fields, J. M., Bodini, N., Lee, J. C. Y., "
                "Todd, A., Simley, E., Hammond, R., Phillips, C., Lunacek, M., Williams, L., "
                "Craig, A., Agarwal, N., Sheng, S., & Meissner, J. (2021). "
                "OpenOA: An Open-Source Codebase For Operational Analysis of Wind Farms. "
                "Journal of Open Source Software, 6(58), 2171."
            ),
            "doi": "10.21105/joss.02171",
        },
    ],
}


# ── Team ──────────────────────────────────────────────────────────────────────

TEAM_MEMBERS = [
    {"name": "Jordan Perr-Sauer", "role": "Lead Developer", "orcid": "0000-0003-1571-1887"},
    {"name": "Mike Optis", "role": "Researcher", "orcid": "0000-0001-5617-6134"},
    {"name": "Jason M. Fields", "role": "Researcher", "orcid": "0000-0002-8781-6138"},
    {"name": "Nicola Bodini", "role": "Researcher", "orcid": "0000-0002-2550-9853"},
    {"name": "Joseph C.Y. Lee", "role": "Researcher", "orcid": "0000-0003-1897-6290"},
    {"name": "Austin Todd", "role": "Developer", "orcid": "0000-0002-1123-0982"},
    {"name": "Eric Simley", "role": "Researcher", "orcid": "0000-0002-1027-9848"},
    {"name": "Robert Hammond", "role": "Developer", "orcid": "0000-0003-4476-6406"},
    {"name": "Caleb Phillips", "role": "Researcher", "orcid": None},
    {"name": "Monte Lunacek", "role": "Developer", "orcid": None},
    {"name": "Lindy Williams", "role": "Researcher", "orcid": None},
    {"name": "Anna Craig", "role": "Researcher", "orcid": None},
    {"name": "Nathan Agarwal", "role": "Developer", "orcid": None},
    {"name": "Shawn Sheng", "role": "Researcher", "orcid": None},
    {"name": "John Meissner", "role": "Developer", "orcid": None},
]
